[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PhyloCoalSimulations = "53f7b83a-06b5-4910-9a21-1896bf762ade"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
SNaQ = "c2bf7a07-44d2-4d11-b5e2-76dc5aa199d6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
SNaQ = { url = "https://github.com/JuliaPhylo/SNaQ.jl", rev="treechild-galled" }
